###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: v1
description: A helm chart for deploying the cluster lifecycle
name: rcm
appVersion: "1.0"
version: 3.5.0
tillerVersion: ">=2.12.3"
kubeVersion: ">=1.11.0"
keywords:
  - IcpClusterResource
  - Commercial
  - ICP
  - IKS
  - ICPRHOCP
  - Operations
  - amd64
  - ppc64le
  - s390x