# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}.{{ .Release.Name }}.{{ .Values.ClusterClaimsController.shortName }}
  labels:
    app: {{ .Values.ClusterClaimsController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.ClusterClaimsController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.ClusterClaimsController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterclaims","clusterpools"]
  verbs: ["get","list","watch","update","patch"]

- apiGroups:
  - "cluster.open-cluster-management.io"
  - "agent.open-cluster-management.io"
  resources:
  - managedclusters
  - klusterletaddonconfigs
  verbs:
  - get
  - list
  - create
  - delete
  - watch

- apiGroups:
  - "register.open-cluster-management.io"
  resources:
  - managedclusters/accept
  verbs:
  - update

- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - managedclustersets/join
  verbs:
  - create

- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - list
  - get
  - watch
  - delete

# Leader election
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create