# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.org }}:{{ .Release.Name }}:{{ .Values.klusterletAddonController.name }}-v2
  labels:
    app: {{ .Values.klusterletAddonController.name }}-v2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.klusterletAddonController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.klusterletAddonController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - klusterlet-addon-controller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - agent.open-cluster-management.io
  resources:
  - klusterletaddonconfigs
  - klusterletaddonconfigs/finalizers
  - klusterletaddonconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  - manifestworks/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
# appmgr
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - subscriptionreports
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - compliance.mcm.ibm.com
  resources:
  - compliances
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.mcm.ibm.com
  resources:
  - policies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - klusterlets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - deployables
  - channels
  - channels/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - deployables/status
  verbs:
  - patch
  - update
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["action.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["view.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["internal.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["mcm.ibm.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["proxy.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups: 
  - addon.open-cluster-management.io
  resources: 
  - managedclusteraddons
  - managedclusteraddons/status
  - clustermanagementaddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/kube-apiserver-client
  verbs:
  - approve
- apiGroups:
    - imageregistry.open-cluster-management.io
  resources:
    - managedclusterimageregistries
    - managedclusterimageregistries/status
  verbs:
    - get
    - list
    - watch
