# Copyright Contributors to the Open Cluster Management project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ProviderCredentialController.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ProviderCredentialController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.ProviderCredentialController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.ProviderCredentialController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.ProviderCredentialController.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.ProviderCredentialController.name }}
    spec:
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      {{- with .Values.clusterCuratorAffinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubconfig.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.ProviderCredentialController.shortName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      containers:
      - name: {{ .Values.OldProviderConnectionController.name }}
        command: 
        - "./old-provider-connection"
        - "-enable-leader-election"
        image: "{{ .Values.global.imageOverrides.provider_credential_controller }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
        {{- toYaml .Values.OldProviderConnectionController.resources | nindent 10 }}
      - command:
        - "./manager"
        - "-enable-leader-election"
        image: "{{ .Values.global.imageOverrides.provider_credential_controller }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        name: {{ .Values.ProviderCredentialController.name }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
        {{- toYaml .Values.ProviderCredentialController.resources | nindent 10 }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
